const $=(s,p=document)=>p.querySelector(s), $$=(s,p=document)=>[...p.querySelectorAll(s)];
const stars=$('.stars'); for(let i=0;i<45;i++){const x=document.createElement('i');x.style.left=`${(i*37)%100}%`;x.style.top=`${(i*67)%100}%`;x.style.animationDelay=`${(i%9)*.4}s`;stars.appendChild(x)}
const menu=$('#menu');$('.menu-button').addEventListener('click',()=>menu.classList.toggle('open'));$$('#menu a').forEach(a=>a.addEventListener('click',()=>menu.classList.remove('open')));
const albumModal=$('#album-modal'), photoModal=$('#photo-modal'), albumGrid=$('#album-grid'), albumTitle=$('#album-title'), albumDescription=$('#album-description'), expandedImage=$('#expanded-image'), expandedLabel=$('#expanded-label');
const galleryPhotos={amizades:['img/amizades/1.JPG','img/amizades/2.JPG','img/amizades/16.JPG','img/amizades/21.jpg'],caretas:['img/caretas/DSC02952.JPG','img/caretas/DSC02956.JPG','img/caretas/DSC03294.JPG','img/caretas/DSC03805.JPG'],experimentos:['img/experimentos/DSC04720.JPG','img/experimentos/DSC04722.JPG','img/experimentos/DSC04738.JPG','img/experimentos/IMG-20250412-WA0003.jpg'],junina:['img/festa%20junina/DSC05221.JPG','img/festa%20junina/DSC05226.JPG','img/festa%20junina/DSC05227.JPG'],despedida:['img/despedida/DSC04002.JPG','img/despedida/DSC04539.JPG','img/despedida/DSC04540.JPG'],trotes:['img/trotes/DSC05426.JPG','img/trotes/DSC05427.JPG','img/trotes/DSC05428.JPG','img/trotes/DSC05429.JPG']};
const galleryNames={amizades:'Amizades',caretas:'Caretas',experimentos:'Experimentos',junina:'Festa Junina',despedida:'Despedidas',trotes:'Trotes'};
$$('.album').forEach(album=>album.querySelector('button').addEventListener('click',()=>{const key=album.dataset.gallery,photos=galleryPhotos[key]||[];albumTitle.textContent=galleryNames[key]||key;albumDescription.textContent=`${photos.length} fotos desta parte da nossa história. Clique em qualquer uma para ampliar.`;albumGrid.innerHTML='';photos.forEach((src,index)=>{const b=document.createElement('button');b.className='album-thumb';b.innerHTML=`<img src="${src}" alt="${galleryNames[key]||key} · foto ${index+1}" loading="lazy"><small>foto ${String(index+1).padStart(2,'0')}</small>`;b.addEventListener('click',()=>openExpanded(src,`${galleryNames[key]||key} · foto ${String(index+1).padStart(2,'0')}`));albumGrid.appendChild(b)});albumModal.classList.remove('hidden')}));
function openExpanded(src,label){expandedImage.src=src;expandedImage.alt=label;expandedLabel.textContent=label;photoModal.classList.remove('hidden')}
$$('.modal-close',albumModal).forEach(b=>b.addEventListener('click',()=>albumModal.classList.add('hidden')));$$('.modal-close',photoModal).forEach(b=>b.addEventListener('click',()=>photoModal.classList.add('hidden')));albumModal.addEventListener('click',e=>{if(e.target===albumModal)albumModal.classList.add('hidden')});photoModal.addEventListener('click',e=>{if(e.target===photoModal)photoModal.classList.add('hidden')});
const people=['Mathues Xavier','Clara','Larisa','David','Emanuela','Gusttavo','Cezar','Isabelle','Kecio','Gledersson','Athos','Victor Henrique','Francisco','Ryan Silva','Mathues Valadares','João Nicolas','Vinicius Souza','Gabriel','Kauan','Matheus Santos','Rafael Yuuta','Victor Correia','Felipe Correia','Guilherme Bueno','Ryan Matos','Patrick','Carlos','Lucas Lopez'];
const search=$('#name-search'),results=$('#search-results'),unlock=$('#unlock-modal'),answer=$('#answer');let selected='';
search.addEventListener('input',()=>{const term=search.value.trim().toLowerCase();results.innerHTML='';if(!term)return;const matches=people.filter(p=>p.toLowerCase().includes(term)).slice(0,6);if(!matches.length){results.innerHTML='<p class="search-result">Nenhuma cápsula encontrada.</p>';return}matches.forEach(person=>{const b=document.createElement('button');b.className='search-result';b.innerHTML=`<span><strong>${person}</strong><small>Existe uma lembrança aqui.</small></span><span>↗</span>`;b.addEventListener('click',()=>{selected=person;answer.value='';unlock.classList.remove('hidden');setTimeout(()=>answer.focus(),80)});results.appendChild(b)})});
function close(el){el.classList.add('hidden')}$('.modal-close',unlock).addEventListener('click',()=>close(unlock));unlock.addEventListener('click',e=>{if(e.target===unlock)close(unlock)});
function unlockMemory(){const value=answer.value.trim().toLowerCase();if(value==='matemática'||value==='matematica'){close(unlock);$('.private-greeting').textContent=`${selected||'Clara'}, isso aqui é para você.`;$('#private-memory').classList.remove('hidden');setTimeout(()=>$('#private-memory').scrollIntoView({behavior:'smooth'}),80)}else{answer.animate([{transform:'translateX(-5px)'},{transform:'translateX(5px)'},{transform:'translateX(0)'}],{duration:220})}}
$('#unlock-button').addEventListener('click',unlockMemory);answer.addEventListener('keydown',e=>{if(e.key==='Enter')unlockMemory()});$('#close-private').addEventListener('click',()=>$('#private-memory').classList.add('hidden'));document.addEventListener('keydown',e=>{if(e.key==='Escape'){close(galleryModal);close(unlock);$('#private-memory').classList.add('hidden')}});
